name: ci-hello
# on: push
on:
  push:
    branches-ignore:
      - master

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: ci-workflow-test
        run: echo "This workflow should not run on the master branch"
        # run: echo "Hello World!"